version: '3.5'

services:
  proxy:
      build: ./proxy-docker
      restart: always
      ports:
        - 80:80
        - 443:443
      labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
      volumes:
        - certs:/etc/nginx/certs:ro
        - vhost.d:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/tmp/docker.sock:ro
      networks:
        - proxy-tier

  letsencrypt-companion:
      image: jrcs/letsencrypt-nginx-proxy-companion
      restart: always
      volumes:
        - certs:/etc/nginx/certs
        - vhost.d:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
      networks:
        - proxy-tier
      depends_on:
        - proxy

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
   name: "proxy_net"